### ISSUE TITLE
[tracking] io

### ISSUE THREAD

**Issue by yoshuawuyts** [async-rs/async-std#131]
Similar to #129 for streams, this issue tracks what's left to port from [`std::io`](https://doc.rust-lang.org/std/io/index.html) to [`async_std::io`](https://docs.rs/async-std/0.99.4/async_std/io/index.html).

## Top-level exports
- `prelude`

## Free functions
- [x] `copy`
- [x] `empty`
- [x] `repeat`
- [x] `sink`
- [x] `stderr`
- [x] `stdin`
- [x] `stdout`

## Structs
- [x] `BufReader`
- [x] `BufWriter`
- [x] `Bytes`
- [x] `Chain`
- [x] `Cursor`
- [x] `Empty`
- [x] `Error`
- [x] `IntoInnerError`
- [x] `IoSlice`
- [x] `IoSliceMut`
- [ ] `LineWriter`
- [x] `Lines`
- [x] `Repeat`
- [x] `Sink`
- [x] `Split`
- [x] `Stderr`
- [x] `StderrLock`
- [x] `Stdin`
- [x] `StdinLock`
- [x] `Stdout`
- [x] `StdoutLock`
- [x] `Take`

## `Read` methods
- [x] `Read::by_ref`
- [x] `Read::bytes`
- [x] `Read::chain`
- [x] `Read::read_exact`
- [x] `Read::read_to_end`
- [x] `Read::read_to_string`
- [x] `Read::read_vectored`
- [x] `Read::take`

## `Write` methods
- [ ] `Write::by_ref`
- [x] `Write::write_all`
- [x] `Write::write_fmt`
- [x] `Write::write_vectored`

## `BufRead` methods
- [x] `BufRead::buffer`
- [x] `BufRead::consume`
- [x] `BufRead::lines`
- [x] `BufRead::read_line`
- [x] `BufRead::read_until`
- [x] `BufRead::split`

## `BufWriter` methods
- [x] `BufWriter::buffer`
- [x] `BufWriter::get_mut`
- [x] `BufWriter::get_ref`
- [x] `BufWriter::into_inner`
- [x] `BufWriter::new`
- [x] `BufWriter::with_capacity`

## `BufReader` methods
- [x] `BufReader::fill_buf`
- [x] `BufReader::get_mut`
- [x] `BufReader::get_ref`
- [x] `BufReader::into_inner`
- [x] `BufReader::new`
- [x] `BufReader::with_capacity`

**Comment by taiki-e** [comment]
Note that this list contains unstable APIs.

**Comment by yoshuawuyts** [comment]
@taiki-e ah dang, you're right. Perhaps we should keep those out for now.

**Comment by yoshuawuyts** [comment]
Gone and filtered out all the experimental APIs!

**Comment by dignifiedquire** [comment]
Missing exports for the return values of 

- `io::Read::take`
- `io::Read::bytes`
