### ISSUE TITLE
[tracking] fmt

### ISSUE THREAD

**Issue by dignifiedquire** [async-rs/async-std#247]
When trying to implement `io::Write::write_fmt`, I ran into the issue that the implementation requires the use of a second `Write` trait, the one in `fmt`. 

If we want to properly implement this, I believe an async version of that is required as well, which in turn triggers usages like implementing the `write!` macro in an async form. 

Ref: #245 #131 

Usage: https://github.com/rust-lang/rust/blob/master/src/libstd/io/mod.rs#L1412

# Tracking List

## Structs

- [x] `Arguments` (re-export)
- [x] `DebugList` (re-export)
- [x] `DebugMap` (re-export)
- [x] `DebugSet` (re-export)
- [x] `DebugStruct` (re-export)
- [x] `DebugTuple` (re-export)
- [x] `Error` (re-export)
- [x] `Formatter` (re-export)

## Enums

- [x] `Alignment` (re-export)

## Traits

- [x] `Binary`  (re-export)
- [x] `Debug`  (re-export)
- [x] `Display`  (re-export)
- [x] `LowerExp`  (re-export)
- [x] `LowerHex`  (re-export)
- [x] `Octal`  (re-export)
- [x] `Pointer`  (re-export)
- [x] `UpperExp`  (re-export)
- [x] `UpperHex`  (re-export)
- [x] `Write`

## Functions

- [x] `fmt::format` (re-export)
- [ ] `fmt::write`

## Type Defintions

- [x] `Result` (re-export)

**Comment by yoshuawuyts** [comment]
@dignifiedquire as we've talked about in chat, I agree with the reasoning here and we should indeed create a new `fmt` submodule.

I'll update your initial comment to include a list of things to port, and label this as a tracking issue.

**Comment by stjepang** [comment]
I don't think we need an async version of `std::fmt::Write` because that trait is only implemented on `String` and `Formatter`, which are not async data structures.

The only part of `fmt` that could be asyncified, I think, is the `std::fmt::write` function. But it's not used that often in practice and we could just provide an async version of the `write!` macro instead.

**Comment by yoshuawuyts** [comment]
> The only part of fmt that could be asyncified, I think, is the std::fmt::write function. But it's not used that often in practice and we could just provide an async version of the write! macro instead.

Just checked the signatures and I think I'm mostly agreeing here tbh. The macro seems relatively straight forward too: https://doc.rust-lang.org/src/core/macros.rs.html#388-390.

Okay yeah I'm on board with not implementing `async_std::fmt`, and relying on `std::fmt::Write` instead. As for the specific implementation here: I think we should probably write some custom code for the implementation as `std::fmt::Write` doesn't seem to appear in any signatures.

@dignifiedquire how does this sound?
